import type { Metadata } from "next";
import { Playwrite_IN} from "next/font/google";
import "./globals.css";


const playwrite = ({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400'],
  display: 'swap',
  variable: '--font-playwrite',
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${playwrite.variable}`} >
      <body
        
      >
        {children}
      </body>
    </html>
  );
}
