import { NextRequest, NextResponse } from "next/server";
import axios from "axios";
import { cookies } from 'next/headers';

export async function GET(req: NextRequest) {
  try {
    const code = req.nextUrl.searchParams.get("code");
    const state = req.nextUrl.searchParams.get("state");
    const error = req.nextUrl.searchParams.get("error");

    // Check if user denied access
    if (error) {
      return NextResponse.redirect(`${process.env.NEXTAUTH_URL}?error=access_denied`);
    }

    if (!code) {
      return new NextResponse("Missing authorization code", { status: 400 });
    }
    
    // Get cookies
    const cookieStore = await cookies();
    const storedState = cookieStore.get('spotify_auth_state')?.value;

    // Validate state
    if (!state || state !== storedState) {
      return new NextResponse("Invalid state parameter", { status: 400 });
    }

    // Get stored data from cookies
    const mood = cookieStore.get('spotify_mood')?.value;
    const songs = JSON.parse(cookieStore.get('spotify_songs')?.value || "[]");

    // Cleanup cookies
    cookieStore.delete('spotify_auth_state');
    cookieStore.delete('spotify_mood');
    cookieStore.delete('spotify_songs');

    // FIXED: Use proper redirect_uri format and Basic Auth
    const redirectUri = `${process.env.NEXTAUTH_URL}/api/spotify-auth`;
    
    // Create Basic Auth header (recommended by Spotify)
    const basicAuth = Buffer.from(
      `${process.env.SPOTIFY_CLIENT_ID}:${process.env.SPOTIFY_CLIENT_SECRET}`
    ).toString('base64');

    // Exchange code for tokens
    const tokenResponse = await axios.post(
      "https://accounts.spotify.com/api/token",
      new URLSearchParams({
        grant_type: "authorization_code",
        code: code,
        redirect_uri: redirectUri,
      }).toString(),
      {
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          "Authorization": `Basic ${basicAuth}`,
        },
      }
    );

    const accessToken = tokenResponse.data.access_token;

    // Get user profile to ensure token works
    const userResponse = await axios.get("https://api.spotify.com/v1/me", {
      headers: { Authorization: `Bearer ${accessToken}` },
    });

    // Create playlist
    const playlistResponse = await axios.post(
      `https://api.spotify.com/v1/users/${userResponse.data.id}/playlists`,
      {
        name: `Beats on Feels: ${mood || 'Mixed'} - ${new Date().toLocaleDateString()}`,
        description: `Generated by Beats on Feels based on your ${mood || 'current'} mood`,
        public: false, // Changed to false for privacy
      },
      {
        headers: { Authorization: `Bearer ${accessToken}` },
      }
    );

    // Search tracks with better error handling
    const trackUris = await Promise.all(
      songs.map(async (song: string) => {
        try {
          const searchResponse = await axios.get(
            `https://api.spotify.com/v1/search`,
            {
              params: {
                q: song,
                type: 'track',
                limit: 1,
              },
              headers: { Authorization: `Bearer ${accessToken}` },
            }
          );
          return searchResponse.data.tracks.items[0]?.uri;
        } catch (err) {
          console.error(`Failed to find track: ${song}`, err);
          return null;
        }
      })
    );

    const validUris = trackUris.filter((uri): uri is string => uri !== null);

    if (validUris.length === 0) {
      return new NextResponse("No tracks found", { status: 404 });
    }

    // Add tracks to playlist
    await axios.post(
      `https://api.spotify.com/v1/playlists/${playlistResponse.data.id}/tracks`,
      { uris: validUris },
      {
        headers: { Authorization: `Bearer ${accessToken}` },
      }
    );

    // Redirect to the created playlist
    return NextResponse.redirect(playlistResponse.data.external_urls.spotify);
  } catch (error) {
    console.error("Spotify auth error:", error);
    
    if (axios.isAxiosError(error)) {
      console.error("Response data:", error.response?.data);
      console.error("Response status:", error.response?.status);
    }
    
    return NextResponse.redirect(
      `${process.env.NEXTAUTH_URL}?error=playlist_failed`
    );
  }
}